---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gpu.nvidia.com
  resources:
  - gpuhealths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gpu.nvidia.com
  resources:
  - gpuhealths/finalizers
  verbs:
  - update
- apiGroups:
  - gpu.nvidia.com
  resources:
  - gpuhealths/status
  verbs:
  - get
  - patch
  - update
