FROM nvidia/dcgm:4.5.2-1-ubuntu22.04
WORKDIR /workspace
RUN rm -rf /usr/local/go && \
  apt-get update && apt-get install -y --no-install-recommends ca-certificates curl build-essential && \
  rm -rf /var/lib/apt/lists/* && \
  curl -LO https://go.dev/dl/go1.26.6.linux-amd64.tar.gz && \
  tar -C /usr/local -xzf go1.26.6.linux-amd64.tar.gz && \
  rm go1.26.6.linux-amd64.tar.gz

ENV PATH="${PATH}:/usr/local/go/bin"

COPY go.mod go.sum ./
RUN go mod download
COPY ./internal/ ./internal/

ENTRYPOINT [ "go", "test", "-tags=integration", "-v", "./internal/injector/..." ]
