FROM golang:1.26 AS builder
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY ./cmd/gpu-injector .
RUN CGO_ENABLED=1 GOOS=linux go build -o /out/gpu-injector ./

FROM nvidia/dcgm:4.5.2-1-ubuntu22.04
COPY --from=builder /out/ /usr/local/bin
ENTRYPOINT [ "gpu-injector" ]
