name: Integration Tests

on:
  push:
    paths:
    - 'internal/injector/**'
    - 'hack/demo/Dockerfile.gpu-injector*'
  pull_request:
    paths:
    - 'internal/injector/**'
    - 'hack/demo/Dockerfile.gpu-injector*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker build -f ./hack/demo/Dockerfile.gpu-injector-tests -t gpu-injector-tests:latest .
      - run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock gpu-injector-tests:latest
